# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bindi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bindi
   pod "MBCircularProgressBar"

  target 'BindiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BindiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
